# Albert QWxiZXJ0
# Betty QmV0dHk=
# Charles Q2hhcmxlcw==

### should create a new account when requested
POST http://localhost:3000/accounts
Accept: application/json
Cache-Control: no-cache

{
  "name": "Charles"
}

### should return 401 when authentication token is not recognized
GET http://localhost:3000/accounts/1/operations/
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer BadToken

### should return 403 when user id and account id don't match
GET http://localhost:3000/accounts/2/operations/
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer QWxiZXJ0